spring:
  thymeleaf:
    cache: false

  data:
    rest:
      base-path: /data-api

  artemis:
    password: test
    user: test
    broker-url: tcp://localhost:61616

  jms:
    template:
      default-destination: tacocloud.order.queue

  rabbitmq:
    template:
      exchange: tacocloud.order
      routing-key: kitchen.central

  kafka:
    bootstrap-servers:
      - localhost:9092
    template:
      default-topic: tacocloud.orders.topic

  datasource:
    url: jdbc:h2:mem:tacocloud
    generate-unique-name: false
    name: tacocloud
    username: user
    password: user
    driverClassName: org.h2.Driver

  main:
    allow-bean-definition-overriding: true

  h2:
    console.enabled: true

server:
  port: 8443
  ssl:
    key-store: classpath:mykeys.jks
    key-store-password: NPoab92001
    key-password: NPoab92001
    key-alias: tomcat


#  security:
#    oauth2:
#      client:
#        registration:
#          facebook:
#          clientId: <facebook client id>
#          clientSecret: <facebook client secret>
#          scope: email, public_profile


taco:
  orders:
    page-size: 20


tacocloud:
  email:
    host: imap.tacocloud.com
    mailbox: INBOX
    username: taco-in-flow
    password: secret
    poll-rate: 10000

  api:
    url: http://localhost:8080/orders/fromEmail
